import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Printer, FileText } from '@phosphor-icons/react';

export default function Reports({ calculationResult }) {
  const r = calculationResult || (() => {
    const saved = sessionStorage.getItem('ait-result');
    return saved ? JSON.parse(saved) : null;
  })();

  const handlePrint = () => window.print();

  if (!r) {
    return (
      <div className="max-w-4xl mx-auto space-y-6" data-testid="reports-page">
        <h1 className="font-heading text-2xl md:text-3xl font-semibold tracking-tight flex items-center gap-2"><FileText size={24} /> PDF Reports</h1>
        <Card className="rounded-sm border"><CardContent className="p-8 text-center text-sm text-muted-foreground">No calculation data available. Complete a calculation first, then generate a report.</CardContent></Card>
      </div>
    );
  }

  const pe = r.plain_english || {};

  return (
    <div className="max-w-4xl mx-auto space-y-6" data-testid="reports-page">
      <div className="flex items-center justify-between no-print">
        <div>
          <h1 className="font-heading text-2xl md:text-3xl font-semibold tracking-tight flex items-center gap-2"><FileText size={24} /> PDF Report</h1>
          <p className="text-sm text-muted-foreground mt-1">Print or save as PDF for records and audits.</p>
        </div>
        <Button className="rounded-sm" onClick={handlePrint} data-testid="print-report-btn"><Printer size={16} className="mr-2" /> Print / Save as PDF</Button>
      </div>

      {/* Printable Report */}
      <Card className="rounded-sm border" id="printable-report">
        <CardContent className="p-8 space-y-6">
          <div className="border-b pb-4">
            <h2 className="text-lg font-heading font-bold">Shift Pay Calculation Report</h2>
            <p className="text-xs text-muted-foreground">Generated: {new Date().toLocaleString()}</p>
          </div>

          {/* Summary */}
          <div className="grid grid-cols-3 gap-4">
            <div className="border rounded-sm p-3"><p className="text-[10px] uppercase text-muted-foreground">Total Hours</p><p className="text-lg font-mono font-bold">{r.total_hours}hrs</p></div>
            <div className="border rounded-sm p-3"><p className="text-[10px] uppercase text-muted-foreground">Estimated Pay</p><p className="text-lg font-mono font-bold">${r.estimated_pay.toFixed(2)}</p></div>
            <div className="border rounded-sm p-3"><p className="text-[10px] uppercase text-muted-foreground">Break Status</p><p className={`text-lg font-mono font-bold ${r.break_status === 'Compliant' ? 'text-emerald-600' : 'text-red-500'}`}>{r.break_status}</p></div>
          </div>

          {/* Components */}
          <div>
            <h3 className="text-sm font-semibold mb-2">Pay Components</h3>
            <table className="w-full text-xs border-collapse">
              <thead><tr className="border-b"><th className="text-left py-1">Component</th><th className="text-right py-1">Qty</th><th className="text-right py-1">Rate</th><th className="text-right py-1">Amount</th><th className="text-left py-1 pl-3">Clause</th></tr></thead>
              <tbody>
                {r.components.map((c, i) => (
                  <tr key={i} className="border-b"><td className="py-1">{c.component}</td><td className="text-right py-1 font-mono">{c.quantity}</td><td className="text-right py-1 font-mono">${c.unit_rate}</td><td className="text-right py-1 font-mono font-bold">${c.amount.toFixed(2)}</td><td className="py-1 pl-3 text-muted-foreground">{c.clause}</td></tr>
                ))}
                <tr className="font-bold"><td className="py-1" colSpan={3}>TOTAL</td><td className="text-right py-1 font-mono">${r.estimated_pay.toFixed(2)}</td><td></td></tr>
              </tbody>
            </table>
          </div>

          {/* Plain English */}
          <div className="space-y-3">
            <h3 className="text-sm font-semibold">Explanation</h3>
            {['section_a', 'section_b', 'section_c', 'section_d', 'section_e'].map(k => (
              <div key={k} className="border-l-2 border-border pl-3">
                <p className="text-[10px] font-semibold uppercase">{k.replace('section_', 'Section ')}</p>
                <p className="text-xs text-muted-foreground whitespace-pre-line">{pe[k] || 'N/A'}</p>
              </div>
            ))}
          </div>

          <div className="border-t pt-4 text-[10px] text-muted-foreground">
            <p>This report is generated by the Award Interpreter Tool for estimation purposes only. Verify all calculations with a qualified payroll professional.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
